#!/bin/sh

# Run the linting script
npm exec lint-staged

# Capture the exit code of the lint command
if [ $? -ne 0 ]; then
  echo "Linting failed! Please fix the errors before committing."
  exit 1
fi
