<?php
/**
 * Name: Watch URL Health
 * Description: Decide whether a probed provider URL is still a working provider.
 *
 * Pure: no network, no state, no globals, no queries. It touches WordPress only
 * for `wp_parse_url()` and the translation functions, both of which the test
 * bootstrap shims, so it is unit-testable without a WP runtime (see
 * tests/unit/CPTs/WatchUrlHealthTest). The HTTP request that feeds it lives in
 * Watch_Hosts::probe().
 *
 * A dead Ways to Watch link is the easy case -- a 404 says so. The expensive
 * case is the one that still returns HTTP 200: Quibi shut down and quibi.com is
 * now an online casino, so every reader who clicked that button got sent
 * somewhere we did not intend. Status codes cannot see that, which is why this
 * also looks at three cheap signals:
 *
 *   - the domain now serves a parking / for-sale page
 *   - the request ends up on a different registrable domain than it started on
 *   - the site no longer calls itself anything resembling our provider name
 *
 * None of these are proof, so they report as 'review' rather than 'broken'. The
 * job here is to put a human in front of the twenty URLs worth looking at, not
 * to decide anything on its own.
 *
 * @package LWTV
 */

namespace LWTV\CPTs\Shows;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Watch_Url_Health {

	/**
	 * Outcomes, worst first.
	 *
	 * - BROKEN:  the URL cannot serve a reader. Fix or remove it.
	 * - REVIEW:  it answered, but something says it may not be the provider any
	 *            more. Needs eyes.
	 * - BLOCKED: it refused *us* specifically. Almost always fine for readers;
	 *            reported so a real problem isn't hidden inside a 403.
	 * - OK:      nothing to say.
	 */
	const STATUS_BROKEN  = 'broken';
	const STATUS_REVIEW  = 'review';
	const STATUS_BLOCKED = 'blocked';
	const STATUS_OK      = 'ok';

	/**
	 * Shortest normalised name we'll compare on.
	 *
	 * Two-character names ('GO', for go.com) collide with far too much ordinary
	 * text to be evidence either way, so they're treated as unjudgeable rather
	 * than flagged.
	 */
	const MIN_NAME_KEY = 3;

	/**
	 * Strings that mean "this is a parking page, not a site".
	 *
	 * Two kinds: copy that parking pages print, and the hostnames of the parking
	 * and domain-brokerage services themselves, which show up in the page's own
	 * assets and links. All lowercase; the body is lowercased before matching.
	 */
	const PARKED_MARKERS = array(
		// Parking-page copy.
		'this domain is for sale',
		'this domain name is for sale',
		'this domain may be for sale',
		'buy this domain',
		'inquire about this domain',
		'the domain name you requested',
		'the sponsored listings displayed above',
		'this webpage was generated by the domain owner',
		'domain parking',
		'domain is parked',
		'parked domain',
		// Parking and brokerage services.
		'sedoparking.com',
		'parkingcrew.net',
		'bodis.com',
		'above.com/park',
		'afternic.com',
		'hugedomains.com',
		'dan.com/buy-domain',
	);

	/**
	 * Classify one probed URL.
	 *
	 * @param array  $probe     Output of Watch_Hosts::probe(): keys 'error',
	 *                          'code', 'final_url', 'site_name', 'body'.
	 * @param string $term_name The provider term's display name.
	 * @param string $url       The URL that was probed.
	 * @return array{status: string, problem: string}
	 */
	public static function classify( array $probe, string $term_name, string $url ): array {
		$error     = (string) ( $probe['error'] ?? '' );
		$code      = (int) ( $probe['code'] ?? 0 );
		$final_url = (string) ( $probe['final_url'] ?? '' );
		$site_name = (string) ( $probe['site_name'] ?? '' );
		$body      = strtolower( (string) ( $probe['body'] ?? '' ) );

		// The request never completed. DNS is gone, TLS is broken, or it timed
		// out -- all of which a reader would experience too.
		if ( '' !== $error ) {
			return self::result(
				self::STATUS_BROKEN,
				/* translators: %s: error message from the HTTP request. */
				sprintf( __( 'Unreachable: %s', 'lwtv' ), $error )
			);
		}

		$by_code = self::classify_code( $code );

		if ( null !== $by_code ) {
			return $by_code;
		}

		// From here down the URL answered 2xx, so everything is about *what* it
		// answered with.
		if ( self::looks_parked( $body ) ) {
			return self::result(
				self::STATUS_BROKEN,
				__( 'Answers, but serves a domain parking or for-sale page. The provider is gone.', 'lwtv' )
			);
		}

		$moved_to = self::offsite_redirect( $url, $final_url );

		if ( '' !== $moved_to ) {
			return self::result(
				self::STATUS_REVIEW,
				sprintf(
					/* translators: %s: registrable domain the URL now lands on. */
					__( 'Redirects off-site to %s. Check whether this is a rebrand to follow or a domain we lost.', 'lwtv' ),
					$moved_to
				)
			);
		}

		if ( ! self::name_matches( $term_name, $site_name, self::host_of( $url ) ) ) {
			return self::result(
				self::STATUS_REVIEW,
				sprintf(
					/* translators: 1: name the site publishes for itself, 2: our provider term name. */
					__( 'The site now calls itself “%1$s”, which does not resemble “%2$s”. Confirm it is still the same provider.', 'lwtv' ),
					$site_name,
					$term_name
				)
			);
		}

		return self::result( self::STATUS_OK, '' );
	}

	/**
	 * What the status code alone tells us.
	 *
	 * @param int $code HTTP status, or 0 when we never got one.
	 * @return array{status: string, problem: string}|null Null means "2xx, keep looking".
	 */
	private static function classify_code( int $code ): ?array {
		if ( $code >= 200 && $code < 300 ) {
			return null;
		}

		// A completed request with no status code should not happen, but a
		// silent pass here would look like a healthy URL.
		if ( 0 === $code ) {
			return self::result( self::STATUS_BROKEN, __( 'No HTTP status was returned. Check the URL by hand.', 'lwtv' ) );
		}

		if ( 404 === $code || 410 === $code ) {
			return self::result(
				self::STATUS_BROKEN,
				/* translators: %d: HTTP status code. */
				sprintf( __( 'Gone (HTTP %d). Remove the URL from the term or point it at the current one.', 'lwtv' ), $code )
			);
		}

		if ( in_array( $code, array( 401, 403, 407, 429, 451 ), true ) ) {
			return self::result(
				self::STATUS_BLOCKED,
				/* translators: %d: HTTP status code. */
				sprintf( __( 'Refused our request (HTTP %d). Usually bot-blocking rather than a broken link, but worth one manual check.', 'lwtv' ), $code )
			);
		}

		if ( $code >= 500 ) {
			return self::result(
				self::STATUS_REVIEW,
				/* translators: %d: HTTP status code. */
				sprintf( __( 'Server error (HTTP %d). May be temporary; re-check before changing anything.', 'lwtv' ), $code )
			);
		}

		// The request follows redirects, and blowing the hop limit comes back as
		// a WP_Error, so a 3xx reaching this point means a redirect response with
		// no usable Location header. Leftover 4xx lands here too.
		return self::result(
			self::STATUS_REVIEW,
			/* translators: %d: HTTP status code. */
			sprintf( __( 'Unexpected response (HTTP %d).', 'lwtv' ), $code )
		);
	}

	/**
	 * Does this body look like a parking page?
	 *
	 * @param string $body Lowercased response body.
	 * @return bool
	 */
	public static function looks_parked( string $body ): bool {
		if ( '' === $body ) {
			return false;
		}

		foreach ( self::PARKED_MARKERS as $marker ) {
			if ( false !== stripos( $body, $marker ) ) {
				return true;
			}
		}

		return false;
	}

	/**
	 * The registrable domain a URL ended up on, when that isn't where it started.
	 *
	 * Compared at the registrable domain rather than the full host, so
	 * 'netflix.com' -> 'www.netflix.com' and 'tubitv.com' -> 'tubitv.com/home'
	 * are not news. A host we redirect *to* within the same domain is the
	 * provider's own business.
	 *
	 * @param string $url       URL as stored.
	 * @param string $final_url URL after redirects, or '' when unknown.
	 * @return string Registrable domain landed on, or '' when unchanged/unknown.
	 */
	public static function offsite_redirect( string $url, string $final_url ): string {
		if ( '' === $final_url ) {
			return '';
		}

		$from = Host_Name::registrable_domain( self::host_of( $url ) );
		$to   = Host_Name::registrable_domain( self::host_of( $final_url ) );

		if ( '' === $from || '' === $to || $from === $to ) {
			return '';
		}

		return $to;
	}

	/**
	 * Does the name a site publishes for itself still match what we call it?
	 *
	 * Deliberately generous. A mismatch is only reported when there is something
	 * solid to compare, because the cost of a false positive is an editor
	 * checking a link that was fine, every week, until they stop reading the
	 * report.
	 *
	 * Both our term name and the hostname's own label count as "known": a term
	 * named "Hulu" on hulu.com is confirmed either way, and a term named
	 * "BBC iPlayer" on bbc.co.uk is confirmed by the host even if the site says
	 * only "BBC".
	 *
	 * @param string $term_name Our provider term name.
	 * @param string $site_name What the site published, or '' when it published nothing.
	 * @param string $host      Hostname of the URL probed.
	 * @return bool True when there is no evidence of drift.
	 */
	public static function name_matches( string $term_name, string $site_name, string $host ): bool {
		$found = self::name_key( $site_name );

		// Plenty of sites publish no site name at all. Silence is not evidence.
		if ( strlen( $found ) < self::MIN_NAME_KEY ) {
			return true;
		}

		$known = array(
			self::name_key( $term_name ),
			self::name_key( Host_Name::registrable_label( $host ) ),
		);

		$judgeable = false;

		foreach ( $known as $candidate ) {
			if ( strlen( $candidate ) < self::MIN_NAME_KEY ) {
				continue;
			}

			$judgeable = true;

			if ( str_contains( $found, $candidate ) || str_contains( $candidate, $found ) ) {
				return true;
			}
		}

		// Nothing long enough to compare against, so we cannot say.
		return ! $judgeable;
	}

	/**
	 * Reduce a name to something comparable.
	 *
	 * Case, spacing and punctuation all vary between a term name and an
	 * og:site_name for the same provider ("BBC iPlayer" / "bbc iplayer"), and
	 * none of that variation is meaningful here.
	 *
	 * @param string $value Raw name.
	 * @return string Lowercased alphanumerics only.
	 */
	private static function name_key( string $value ): string {
		$key = preg_replace( '/[^a-z0-9]+/', '', strtolower( $value ) );

		return (string) $key;
	}

	/**
	 * Hostname out of a URL, without needing WordPress.
	 *
	 * @param string $url URL.
	 * @return string Normalised host, or '' when unparseable.
	 */
	private static function host_of( string $url ): string {
		$host = wp_parse_url( $url, PHP_URL_HOST );

		return is_string( $host ) ? Host_Name::normalise( $host ) : '';
	}

	/**
	 * Shape a return value.
	 *
	 * @param string $status  One of the STATUS_* constants.
	 * @param string $problem Human-readable explanation, '' when healthy.
	 * @return array{status: string, problem: string}
	 */
	private static function result( string $status, string $problem ): array {
		return array(
			'status'  => $status,
			'problem' => $problem,
		);
	}
}
