/**
 * Configuration for structure-docs.js
 *
 * The script regenerates the file trees inside docs/plugin-structure.txt and
 * docs/theme-structure.txt from the real filesystem, carrying every existing
 * description across. This file tells it where each tree block lives and which
 * directories are deliberately summarized rather than expanded.
 *
 * Directory modes:
 *   expand  (default) - list the directory's children as tree lines
 *   list              - do not descend; regenerate the description as a comma
 *                       list of child basenames (.php stripped)
 *   opaque            - do not descend; keep the hand-written description as-is
 */

module.exports = {
	/*
	 * Names ignored everywhere. Anything starting with a dot is also ignored
	 * unless it is pinned or already mentioned in a manual block.
	 */
	ignore: [
		'.DS_Store',
		'node_modules',
		'vendor',
		'*.map',
		'.gitkeep',
	],

	/*
	 * Entries emitted even when absent from disk (build output, dependency
	 * trees, anything gitignored). Keyed by path relative to the repo root.
	 */
	pin: {
		'plugins/lwtv-plugin/vendor': 'Composer dependencies (not stored in GitHub)',
		'plugins/lwtv-plugin/node_modules': 'npm dependencies (not stored in GitHub)',
		'plugins/lwtv-plugin/php/blocks/build': 'Built block output (generated by @wordpress/scripts - never edit)',
		'plugins/lwtv-plugin/php/blocks/node_modules': 'npm dependencies (not stored in GitHub)',
		'_build_scripts/webpackdist': 'Gitignored webpack output staging dir (`css/`, `js/`) that postbuild.js copies from',
		'_build_scripts/tmp-icons': 'Disposable local clone of the private symbolicons repo, created by symbolicons.js',
	},

	/*
	 * Per-directory modes. Keys are repo-relative paths and may use `*` to
	 * match a single path segment.
	 */
	dirModes: {
		// Statistics view templates are summarized as comma lists.
		'plugins/lwtv-plugin/php/statistics/templates/actors': 'list',
		'plugins/lwtv-plugin/php/statistics/templates/characters': 'list',
		'plugins/lwtv-plugin/php/statistics/templates/death': 'list',
		'plugins/lwtv-plugin/php/statistics/templates/main': 'list',
		'plugins/lwtv-plugin/php/statistics/templates/nations': 'list',
		'plugins/lwtv-plugin/php/statistics/templates/shows': 'list',
		'plugins/lwtv-plugin/php/statistics/templates/stations': 'list',

		// Prose-summarized or vendored trees.
		'plugins/lwtv-plugin/php/blocks/src/*': 'opaque',
		'plugins/lwtv-plugin/php/admin-color-schemes/*': 'opaque',
		'plugins/lwtv-plugin/php/calendar/ICal': 'opaque',
		'plugins/lwtv-plugin/php/plugins/acf/css': 'expand',
		'inc/bootstrap': 'opaque',
		'tests/unit/*': 'opaque',
	},

	docs: [
		{
			file: 'docs/plugin-structure.txt',
			blocks: [
				{
					label: '## Files - `/plugins/lwtv-plugin/`',
					root: 'plugins/lwtv-plugin',
				},
			],
		},
		{
			file: 'docs/theme-structure.txt',
			blocks: [
				{ label: 'PHP Files:', root: '.', filesOnly: true, include: [ '*.php' ] },
				{
					label: 'CSS Files:',
					root: '.',
					filesOnly: true,
					include: [ '*.css', '*.css.map', '*.scss' ],
					// style.css.map / style-editor.css.map are listed on purpose.
					unignore: [ '*.css.map' ],
				},
				// Hand-maintained: groups files and folders that do not form a tree.
				{ label: 'Config / meta files:', manual: true },
				{ label: '## Images - `/images/`', root: 'images' },
				{ label: '## Page Templates - `/page-templates/`', root: 'page-templates' },
				{ label: '## Sass Files - `/scss/`', root: 'scss' },
				{ label: '## Theme Includes - `/inc/`', root: 'inc' },
				// Two sibling mini-trees under one heading; left alone.
				{ label: '### Search WP:', manual: true },
				{ label: '## Template Parts - `/template-parts/`', root: 'template-parts' },
				{ label: '## Build Scripts - `/_build_scripts/`', root: '_build_scripts' },
				{
					label: '## Symbolicons - `/symbolicons/`',
					root: 'symbolicons',
					include: [ '*.json' ],
				},
				{ label: '## Languages - `/languages/`', root: 'languages' },
				{ label: '## Tests - `/tests/`', root: 'tests' },
				{ label: '## Cron - `/cron/`', root: 'cron' },
				{ label: '## Docs - `/docs/`', root: 'docs', maxDepth: 1 },
			],
		},
	],
};
