name: 'Deploy Theme to Development'

on:
  push:
    branches: [ development ]

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Do a git checkout including submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Verify Workspace
        run: |
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"

      - name: Verify Folder
        run: |
          ls -lah ${GITHUB_WORKSPACE}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build it
        run: npm run build

      - name: Deploy to LezWatch.TV Dev Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.LWTV_SSH_KEY }}
          ARGS: "-rlgoDzvc -i"
          REMOTE_HOST: ${{ secrets.LWTV_HOST }}
          REMOTE_USER: ${{ secrets.LWTV_USER }}
          TARGET: /home/${{ secrets.LWTV_USER }}/${{ secrets.LWTV_DEV_DOMAIN }}/wp-content/themes/lwtv-underscores
          EXCLUDE: "/.git/, /.github/, /.husky/, /.sass-cache/, /.vscode/, /node_modules/, /vendor/, .browserslistrc, .gitignore, .npmrc, .nvmrc, .ruby-version, composer.json, composer.lock, package-lock.json, package.json, phpcs.xml.dist, /plugins/lwtv-plugin/node_scripts/, /plugins/lwtv-plugin/node_modules/, /plugins/lwtv-plugin/vendor/, /plugins/lwtv-plugin/.gitignore, /plugins/lwtv-plugin/composer.json, /plugins/lwtv-plugin/composer.lock, /plugins/lwtv-plugin/package-lock.json, /plugins/lwtv-plugin/package.json, /plugins/lwtv-plugin/blocks/node_modules/, /plugins/lwtv-plugin/blocks/.editorconfig, /plugins/lwtv-plugin/blocks/.gitignore, /plugins/lwtv-plugin/blocks/package-lock.json, /plugins/lwtv-plugin/blocks/package.json"
