name: OSV-Scanner

on:
  pull_request:
    branches: [ "production" ]
  merge_group:
    branches: [ "production" ]
  schedule:
    - cron: '26 18 * * 2'
  push:
    branches: [ "production" ]

permissions:
  # Require writing security events to upload SARIF file to security tab
  security-events: write
  # Read commit contents
  contents: read

jobs:
  scan-scheduled:
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.6.0"
    with:
      # Example of specifying custom arguments
      scan-args: |-
        -r
        --skip-git
        ./
