name: 'Deploy Theme to Production'

on:
  push:
    branches: [ production ]

jobs:
  # =======================================
  # JOB 1: Build the theme files
  # =======================================
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Do a git checkout including submodules
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          tools: composer:v2

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build for Production
        run: npm run build

      - name: Upload theme artifact
        uses: actions/upload-artifact@v7
        with:
          name: theme-files-prod
          path: . # Uploads the entire workspace

      - name: Upload cron artifact
        uses: actions/upload-artifact@v7
        with:
          name: cron-files-prod
          path: cron/

  # ========================================================
  # JOB 2: Deploy the built files to the server
  # ========================================================
  deploy:
    runs-on: ubuntu-latest
    needs: build # This ensures the 'build' job finishes first
    steps:
      - name: Download theme artifact
        uses: actions/download-artifact@v8
        with:
          name: theme-files-prod

      - name: Download cron artifact
        uses: actions/download-artifact@v8
        with:
          name: cron-files-prod
          path: cron/ # Specify path to restore directory structure

      - name: Verify Folder Contents
        run: |
          ls -lah
          ls -lah cron/

      - name: Deploy to LezWatch.TV Production Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.LWTV_SSH_KEY }}
          ARGS: "-rlgoDzvc --delete -i"
          REMOTE_HOST: ${{ secrets.LWTV_HOST }}
          REMOTE_USER: ${{ secrets.LWTV_USER }}
          TARGET: /home/${{ secrets.LWTV_USER }}/${{ secrets.LWTV_DOMAIN }}/wp-content/themes/lwtv-underscores
          EXCLUDE: " /_build_scripts/, /.cursor/, /.git/, /.github/, /.githooks/, /.sass-cache/, /.vscode/, /cron/, /docs/, /node_modules/, /scss/, /vendor/, webpack.config.js, .browserslistrc, .gitignore, .npmrc, .nvmrc, .ruby-version, composer.json, composer.lock, package-lock.json, package.json, phpcs.xml.dist, /plugins/lwtv-plugin/node_modules/, /plugins/lwtv-plugin/vendor/, /plugins/lwtv-plugin/.gitignore, /plugins/lwtv-plugin/composer.json, /plugins/lwtv-plugin/composer.lock, /plugins/lwtv-plugin/package-lock.json, /plugins/lwtv-plugin/package.json, /plugins/lwtv-plugin/php/blocks/node_modules/, /plugins/lwtv-plugin/php/blocks/.gitignore, /plugins/lwtv-plugin/php/blocks/package-lock.json, /plugins/lwtv-plugin/php/blocks/package.json, /plugins/lwtv-plugin/php/blocks/.eslint, /plugins/lwtv-plugin/php/src/"

      - name: Deploy Cron to Production Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.LWTV_SSH_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: cron/
          REMOTE_HOST: ${{ secrets.LWTV_HOST }}
          REMOTE_USER: ${{ secrets.LWTV_USER }}
          TARGET: /home/${{ secrets.LWTV_USER }}/cron/

  # =====================================================================
  # JOB 3: Run commands on the server after deployment is complete
  # =====================================================================
  post-deploy:
    runs-on: ubuntu-latest
    needs: deploy # This ensures the 'deploy' job finishes first
    steps:
      - name: Run Post-Deploy Commands on Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LWTV_HOST }}
          username: ${{ secrets.LWTV_USER }}
          key: ${{ secrets.LWTV_SSH_KEY }}
          script: |
            echo "Setting cron permissions..."
            chmod +x /home/${{ secrets.LWTV_USER }}/cron/*.sh

            echo "Copying Symbolicons..."
            cp -r /home/${{ secrets.LWTV_USER }}/symbolicons/production/* /home/${{ secrets.LWTV_USER }}/${{ secrets.LWTV_DOMAIN }}/wp-content/themes/lwtv-underscores/symbolicons/

            echo "Cleaning up login files..."
            rm -f /home/${{ secrets.LWTV_USER }}/logins-*.txt

            echo "Syncing ACF field groups..."
            wp acf json sync --path=/home/${{ secrets.LWTV_USER }}/${{ secrets.LWTV_DOMAIN }}
